# Site settings
title: "Practo Engineering Blog"
logo: logo.svg
email: your-email@domain.com
description: >
    Description goes here
url: "http://practo.github.io"
baseurl: "/"
twitter_username: practo
github_username:  practo

# Build settings
markdown: kramdown
